package: coffee-script
user: javascript

platform:
  # - linux-32
  - linux-64
  - osx-64

install:
  - conda config --file "$CONDARC" -f --add channels https://conda.binstar.org/javascript

script:
  - conda build .

build_targets: conda
