package:
  name: nodejs
  version: 0.10.35

build:
  number: 0

source:
  fn: node-v0.10.35-linux-x64.tar.gz [linux64]
  url: http://nodejs.org/dist/v0.10.35/node-v0.10.35-linux-x64.tar.gz [linux64]
  # sha: 3a202a749492e48542d2c28220e43ef6dae084bc [linux64]
  md5: f3b33eed97772ce3a9341bbeb67511d7 [linux64]

  fn: node-v0.10.35-darwin-x64.tar.gz [osx]
  url: http://nodejs.org/dist/v0.10.35/node-v0.10.35-darwin-x64.tar.gz [osx]
  # sha: 98f61cb09685ed45f2db6e0fc5ccbdd273204091 [osx]
  md5: 7d8e8de66e727e9bc51dead89a7b14cc [osx]

test:
  commands:
    - node --help
    - node --version
    - npm --version

about:
  home: http://nodejs.org/
  license: V8
