package:
  name: node-webkit
  version: '0.11.5'
  
build:
  number: 0
  binary_relocation: false
  has_prefix_files:                                             [win]
    - Scripts\node-webkit.bat                                   [win]

source:
  fn: node-webkit-v0.11.5-linux-ia32.tar.gz                                     [linux32]
  url: http://dl.node-webkit.org/v0.11.5/node-webkit-v0.11.5-linux-ia32.tar.gz  [linux32]

  fn: node-webkit-v0.11.5-linux-x64.tar.gz                                      [linux64]
  url: http://dl.node-webkit.org/v0.11.5/node-webkit-v0.11.5-linux-x64.tar.gz   [linux64]

  fn: node-webkit-v0.11.5-osx-x64.zip                                           [osx]
  url: http://dl.node-webkit.org/v0.11.5/node-webkit-v0.11.5-osx-x64.zip        [osx]
  
  fn: node-webkit-v0.11.5-win-ia32.zip                                          [win]
  url: http://dl.node-webkit.org/v0.11.5/node-webkit-v0.11.5-win-ia32.zip       [win]

about:
  home: https://github.com/rogerwang/node-webkit
  license: MIT
