package: iojs
user: javascript

platform:
  - linux-32
  - linux-64
  - osx-64
  - win-64
  - win-32

script:
  - conda update conda requests --yes --quiet --name=root
  - conda build .

build_targets: conda
