package: iojs
user: javascript

platform:
  - linux-32
  - linux-64
  - osx-64
  - win-64
  - win-32

script:
  - conda install --quiet --yes requests openssl
  - conda list
  - conda build .

build_targets: conda
