package:
  name: iojs
  version: 1.0.3

build:
  number: 0

# Hack to keep from having an empty source on Windows
{% if "HOME" in environ %}
source:
  fn: iojs-v1.0.3-linux-x64.tar.gz [linux64]
  url: https://iojs.org/dist/v1.0.3/iojs-v1.0.3-linux-x64.tar.gz [linux64]
  # sha: 047b75b518767f0983c8159c9bb9a2939a214964ee127890e590af63f9082839 [linux64]
  md5: d49fa446dcd3591d251ed6b78dd83205 [linux64]

  fn: iojs-v1.0.3-linux-x86.tar.gz [linux32]
  url: https://iojs.org/dist/v1.0.3/iojs-v1.0.3-linux-x86.tar.gz [linux32]
  # sha: 7c2d64056b430ebfc46a4f14039d21c1f7fb3fc0c8932eb9da94820e1fee4d1b [linux32]
  md5: 39070179500fbaf17598f5730b954530 [linux32]

  fn: iojs-v1.0.3-darwin-x64.tar.gz [osx]
  url: https://iojs.org/dist/v1.0.3/iojs-v1.0.3-darwin-x64.tar.gz [osx]
  # sha: f390aeb7e5dc553c96afb498c613e8873f1c7a14f7e3f3c2a48e0141aa57eeb1 [osx]
  md5: 93aa8c16d0942c15cc5d7ecac81c2ef2 [osx]
{% endif %}

requirements:
  build:
    - python [win32 and win64]

test:
  commands:
    - iojs --help
    - iojs --version
    - node --version
    - npm --version

about:
  home: https://iojs.org
  license: MIT
